# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: borker.co
email: ryan@borker.co
description: > # this means to ignore newlines until "baseurl:"
  Ryan Borker lives in the space between human judgment and technology. He comes up with products designed to focus time and attention
  on what's important, rather than distractions. Professionally, he founded Shortlist -- a breakthrough approach to executive recruiting.
  In his spare time you'll find him running, writing, taking pictures, or trying out new tea.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://borker.com" # the base hostname & protocol for your site
twitter_username: borker
github_username:  ryanyde

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
markdown: kramdown